* Biologiczne JPKS.
  
** Protokół
  
   Protokół na którym działa bioJPKS jest bardzo prosty.
   Każda informacja jest przesyłana w osobnej lini.

*** Informacja o statusie odpowiedzi
    
    Serwer potwierdza przyjęcie odpowiedzi tagiem =ANSWER=. Gdy odpowiedź jest prawidłowa jest przesyłąna linia =OK=,
    jeżeli padła poprawna odpowiedz od gracza lub =BAD= w przypadku gdy odpowiedź jest zła.

*** Zadawanie pytań

    Serwer informuje o zadanie pytania linijką =QUESTION= po której następuje w nowej lini pytanie, a w następnej linii odpowiedź.
    Do każdego obrazka jest dodawane zdjęcie (Patrz Wysyłanie Obrazków)

*** Wysyłanie obrazków
 
    Serwer może przesłać klientowi obraz rozpoczynając przekaz od linijki =IMAGE= po której w nowej lini
    powinien znajdować się URL do obrazka. Jeżeli obrazek nie jest przesyłany po tagu =IMAGE= pojawia sie tag =DEFAULT=
     
*** Informacje o zawdonikach

    Serwer informuje o aktualnym stanie gry poprzez wysłanie =STATUS= do klientów.
    Zaraz po odebraniu tagu pierwszej nowej lini znajduje się zliczba *n* informująca o ilości zawodników aktualnie 
    biorących udział w rozgrywce. Po niej następuje *n* lini w postaci
    =k nick= gdzie *k* jest liczbą zdobyta przez gracza przestawiającego się jako *nick*. *nick* jest zakończony znakiem nowej lini.
    System nie pozwala na używanie nicków zawierających nową linię.
    

	Po długiej przerwie kończymy projekt:)
	Uważam, że dobrze by było wsadzić nad =OK= i =BAD= jakąś 
nadkomendę. Jednak nie jestem pewien następstw, więc narazie wbijam w 
kodzie RuntimeErrory.

