* Biologiczne JPKS.
  
** Protokół
  
   Protokół na którym działa bioJPKS jest bardzo prosty

*** Informacja o statusie odpowiedzi
    
    Serwer odpowiada o odpowiedz dopiero w momencie udzielenia poprawnej odpowiedzi na pytanie
    liniją =OK= jeżeli padła poprawna odpowiedz od gracza lub =BAD= w przypadku gdy nie padła poprawna odpowiedz

*** Zadawanie pytań

    Serwer informuje o zadanie pytania linijką =QUESTION= po której następuje w nowej lini pytanie.

*** Wysyłanie obrazków
 
    Serwer może przesłać klientowi obraz rozpoczynając przekaz od linijki =IMAGE= po której w nowej lini
    powinien znajdować się URL do obrazka.
     
*** Informacje o zawdonikach

    Serwer informuje o aktualnym stanie gry poprzez wysłanie =STATUS= do klientów.
    Zaraz po odebraniu tagu pierwszej nowej lini znajduje się zliczba *n* informująca o ilości zawodników aktualnie 
    biorących udział w rozgrywce. Po niej następuje *n* lini w postaci
    =k nick= gdzie *k* jest liczbą zdobyta przez gracza przestawiającego się jako *nick*. *nick* jest zakończony znakiem nowej lini.
    System nie pozwala na używanie nicków zawierających nową linię.
    
**Uwagi

	Nie ma tu chyba lepszych możliwości dyskusji, więc modyfikuję readme.
	Uważam, że warto by wprowadzić modyfikacje do protokołu.
	1) Tokeny powinny być w osobnych liniach.
	2) Token =IMAGE= powinien być zawsze przesyłany, a w wypadku, gdy nie chcemy żadnego innego obrazka, w następnej linii powinien znajdować się 
	tekst =DEFAULT=.
